version: '3.7'

networks:
  kafka-net:
    driver: bridge
  db-net:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db-net
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10

  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 9094:9094
    env_file:
      - ./.env
    volumes:
      - ./kafka/data:/var/lib/kafka/data
    networks:
      - kafka-net
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8082:8082
    env_file:
      - ./backend/.env
    depends_on:
      kafka:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - kafka-net
      - db-net

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    env_file:
      - ./producer/.env
    ports:
      - 8081:8081
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - kafka-net

volumes:
  kafka_data:
    driver: local
  postgres-data:
    driver: local
